# Generated by Django 3.2.8 on 2021-10-29 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=511, verbose_name='Вопрос')),
                ('answer', models.CharField(max_length=511, verbose_name='Ответ')),
                ('hint', models.TextField(verbose_name='Подсказка')),
                ('image_origin', models.URLField(verbose_name='URL изображения')),
                ('file_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='File id телеграм')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
    ]
