version: "3"

volumes:
  database:
  certbot-etc:
  certbot-var:
  web-root:

x-services:
  &web-service
  build:
    context: ./web
  env_file:
    - ./web/.env
  volumes:
    - ./web:/app

services:
  web:
    << : *web-service
    restart: unless-stopped
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
  worker:
    << : *web-service
    restart: unless-stopped
    command: dramatiq question_app.actors
  bot:
    restart: unless-stopped
    build:
      context: ./bot
    command: python main.py
    volumes:
      - ./bot:/app
    env_file:
      - ./bot/.env
  database:
    restart: unless-stopped
    image: postgres:13.4-alpine
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
  redis:
    restart: unless-stopped
    image: redis:6.2.6-alpine
  proxy:
    restart: unless-stopped
    image: nginx:1.20.1-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./site.conf:/etc/nginx/conf.d/site.conf
      - ./web/static:/data/static
      - ./web/media:/data/media
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    ports:
      - "443:443"
      - "80:80"
  certbot:
    image: certbot/certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    command: certonly --webroot --webroot-path=/var/www/html --email alex.vidyakov@yandex.ru --agree-tos --no-eff-email --force-renewal -d pdd.televid.site
