# Generated by Django 3.2.8 on 2021-10-29 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=127, null=True, verbose_name='Юзернейм')),
                ('first_name', models.CharField(blank=True, max_length=127, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=127, null=True, verbose_name='Фамилия')),
            ],
            options={
                'verbose_name': 'Пользователь телеграм',
                'verbose_name_plural': 'Пользователи телеграм',
            },
        ),
    ]
