# Generated by Django 3.2.8 on 2021-11-05 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='chosen_query_count',
            field=models.IntegerField(default=0, verbose_name='Количество выбранных вопросов'),
        ),
    ]
