# Generated by Django 3.2.8 on 2021-11-05 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_app', '0002_user_chosen_query_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='payment',
            field=models.BooleanField(default=False, verbose_name='Оплата'),
        ),
    ]
