help = 'Чтобы найти вопрос, нажми на кнопку 👇 и введи свой вопрос после юзернейма бота.'
answer_template = '''❔ {question}

✅ {answer}

💡 {hint}

{image}
'''
purchase_offer = '''<b>Купите  доступ к полной базе ответов на вопросы всего за 99 рублей, чтобы продолжить и успешно сдать на права!</b>

Что дает покупка?
Неограниченный доступ к информации, которая обновляется каждый год, легкий способ сдать экзамен с первой попытки и возможность пользоваться шпаргалкой на любом устройстве.'''
